language: python
python: 2.7
env: PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test
after_success: bin/code-analysis
after_failure: bin/buildout annotate -c travis.cfg
notifications:
  irc: irc.freenode.org#simplesconsultoria
