language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: 45.8.0esr
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  # FIXME: https://github.com/plone/Products.CMFPlone/issues/2126
  allow_failures:
  - env: PLONE_VERSION=5.0
  fast_finish: true
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py --setuptools-version=20.9.0
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install coveralls
- coveralls
after_script:
# Firefox complains: GConf-WARNING **: Got Disconnected from DBus.
# And then it keeps hanging, causing a failed job after 30-50 minutes.
# So we just kill Firefox.
- pkill -9 firefox
notifications:
  irc: irc.freenode.org#plone-testing
